mysql:
  address: "localhost"
  port: 3306
  database: "minecraft"
  username: "root"
  password: ""
  useSSL: true

redis:
  address: "localhost"
  port: 6379

# Register on here https://www.maxmind.com/en/geolite2/signup?lang=en for a free GeoLite2 license key
# Then fill in your license key below and restart the plugin
database:
  license-key: ""
  download-url: "https://download.maxmind.com/app/geoip_download?edition_id=GeoLite2-Country&license_key={LICENSEKEY}&suffix=tar.gz"
  download-if-missing: true
  update:
    enabled: true
    every-x-days: 30

# Turning this setting to true will make it only count the join if they have never joined the server before
only-count-unique: false

# Fill in your domains you wish to track joins for below
domains:
  - "play.example.net:25565"
  - "hub.example.net:25565"
  - "fun.example.net:25565"

# Fill in what each domain should display as when running the command in order
display:
  - "play"
  - "hub"
  - "fun"

# List of every country you can remove unwanted ones if you would like
countries:
  - "Afghanistan"
  - "Albania"
  - "Algeria"
  - "American Samoa"
  - "Andorra"
  - "Angola"
  - "Anguilla"
  - "Antarctica"
  - "Antigua And Barbuda"
  - "Argentina"
  - "Armenia"
  - "Aruba"
  - "Australia"
  - "Austria"
  - "Azerbaijan"
  - "Bahamas"
  - "Bahrain"
  - "Bangladesh"
  - "Barbados"
  - "Belarus"
  - "Belgium"
  - "Belize"
  - "Benin"
  - "Bermuda"
  - "Bhutan"
  - "Bolivia"
  - "Bosnia And Herzegovina"
  - "Botswana"
  - "Bouvet Island"
  - "Brazil"
  - "British Indian Ocean Territory"
  - "Brunei Darussalam"
  - "Bulgaria"
  - "Burkina Faso"
  - "Burundi"
  - "Cambodia"
  - "Cameroon"
  - "Canada"
  - "Cape Verde"
  - "Cayman Islands"
  - "Central African Republic"
  - "Chad"
  - "Chile"
  - "China"
  - "Christmas Island"
  - "Cocos (keeling) Islands"
  - "Colombia"
  - "Comoros"
  - "Congo"
  - "Congo, The Democratic Republic Of The"
  - "Cook Islands"
  - "Costa Rica"
  - "Cote D'ivoire"
  - "Croatia"
  - "Cuba"
  - "Cyprus"
  - "Czech Republic"
  - "Denmark"
  - "Djibouti"
  - "Dominica"
  - "Dominican Republic"
  - "East Timor"
  - "Ecuador"
  - "Egypt"
  - "El Salvador"
  - "Equatorial Guinea"
  - "Eritrea"
  - "Estonia"
  - "Ethiopia"
  - "Falkland Islands (malvinas)"
  - "Faroe Islands"
  - "Fiji"
  - "Finland"
  - "France"
  - "French Guiana"
  - "French Polynesia"
  - "French Southern Territories"
  - "Gabon"
  - "Gambia"
  - "Georgia"
  - "Germany"
  - "Ghana"
  - "Gibraltar"
  - "Greece"
  - "Greenland"
  - "Grenada"
  - "Guadeloupe"
  - "Guam"
  - "Guatemala"
  - "Guinea"
  - "Guinea-bissau"
  - "Guyana"
  - "Haiti"
  - "Heard Island And Mcdonald Islands"
  - "Holy See (vatican City State)"
  - "Honduras"
  - "Hong Kong"
  - "Hungary"
  - "Iceland"
  - "India"
  - "Indonesia"
  - "Iran, Islamic Republic Of"
  - "Iraq"
  - "Ireland"
  - "Israel"
  - "Italy"
  - "Jamaica"
  - "Japan"
  - "Jordan"
  - "Kazakstan"
  - "Kenya"
  - "Kiribati"
  - "Korea, Democratic People's Republic Of"
  - "Korea, Republic Of"
  - "Kosovo"
  - "Kuwait"
  - "Kyrgyzstan"
  - "Lao People's Democratic Republic"
  - "Latvia"
  - "Lebanon"
  - "Lesotho"
  - "Liberia"
  - "Libyan Arab Jamahiriya"
  - "Liechtenstein"
  - "Lithuania"
  - "Luxembourg"
  - "Macau"
  - "Macedonia, The Former Yugoslav Republic Of"
  - "Madagascar"
  - "Malawi"
  - "Malaysia"
  - "Maldives"
  - "Mali"
  - "Malta"
  - "Marshall Islands"
  - "Martinique"
  - "Mauritania"
  - "Mauritius"
  - "Mayotte"
  - "Mexico"
  - "Micronesia, Federated States Of"
  - "Moldova, Republic Of"
  - "Monaco"
  - "Mongolia"
  - "Montserrat"
  - "Montenegro"
  - "Morocco"
  - "Mozambique"
  - "Myanmar"
  - "Namibia"
  - "Nauru"
  - "Nepal"
  - "Netherlands"
  - "Netherlands Antilles"
  - "New Caledonia"
  - "New Zealand"
  - "Nicaragua"
  - "Niger"
  - "Nigeria"
  - "Niue"
  - "Norfolk Island"
  - "Northern Mariana Islands"
  - "Norway"
  - "Oman"
  - "Pakistan"
  - "Palau"
  - "Palestinian Territory, Occupied"
  - "Panama"
  - "Papua New Guinea"
  - "Paraguay"
  - "Peru"
  - "Philippines"
  - "Pitcairn"
  - "Poland"
  - "Portugal"
  - "Puerto Rico"
  - "Qatar"
  - "Reunion"
  - "Romania"
  - "Russian Federation"
  - "Rwanda"
  - "Saint Helena"
  - "Saint Kitts And Nevis"
  - "Saint Lucia"
  - "Saint Pierre And Miquelon"
  - "Saint Vincent And The Grenadines"
  - "Samoa"
  - "San Marino"
  - "Sao Tome And Principe"
  - "Saudi Arabia"
  - "Senegal"
  - "Serbia"
  - "Seychelles"
  - "Sierra Leone"
  - "Singapore"
  - "Slovakia"
  - "Slovenia"
  - "Solomon Islands"
  - "Somalia"
  - "South Africa"
  - "South Georgia And The South Sandwich Islands"
  - "Spain"
  - "Sri Lanka"
  - "Sudan"
  - "Suriname"
  - "Svalbard And Jan Mayen"
  - "Swaziland"
  - "Sweden"
  - "Switzerland"
  - "Syrian Arab Republic"
  - "Taiwan, Province Of China"
  - "Tajikistan"
  - "Tanzania, United Republic Of"
  - "Thailand"
  - "Togo"
  - "Tokelau"
  - "Tonga"
  - "Trinidad And Tobago"
  - "Tunisia"
  - "Turkey"
  - "Turkmenistan"
  - "Turks And Caicos Islands"
  - "Tuvalu"
  - "Uganda"
  - "Ukraine"
  - "United Arab Emirates"
  - "United Kingdom"
  - "United States"
  - "United States Minor Outlying Islands"
  - "Uruguay"
  - "Uzbekistan"
  - "Vanuatu"
  - "Venezuela"
  - "Viet Nam"
  - "Virgin Islands, British"
  - "Virgin Islands, U.s."
  - "Wallis And Futuna"
  - "Western Sahara"
  - "Yemen"
  - "Zambia"
  - "Zimbabwe"