mysql:
  address: "localhost"
  port: 3306
  database: "minecraft"
  username: "root"
  password: ""
  useSSL: false

database:
  license-key: ""
  download-url: "https://download.maxmind.com/app/geoip_download?edition_id=GeoLite2-Country&license_key={LICENSEKEY}&suffix=tar.gz"
  download-if-missing: true
  update:
    enabled: true
    every-x-days: 30

domains:
  - "localhost:25565"
  - "localhost:25565"
  - "localhost:25565"

display:
  - "test1"
  - "test2"
  - "test3"

countries:
  - "United States"
  - "Canada"
  - "United Kingdom"
  - "Netherlands"
  - "Belgium"
  - "Germany"
  - "Australia"
  - "Poland"
  - "Czechia"
  - "Malaysia"
  - "Latvia"
  - "Vietnam"
  - "Sweden"
  - "Austria"
  - "Pakistan"
  - "El Salvador"
  - "Serbia"
  - "France"
  - "New Zealand"
  - "United Arab Emirates"
  - "India"
  - "Spain"
  - "Turkey"
  - "Norway"
  - "Finland"
  - "Denmark"
  - "Mexico"
  - "Brazil"
  - "Unknown"